# Code for Generate Raw Data

## Library

In [28]:
import pandas as pd
from pathlib import Path
import os

## Additional Function

In [29]:
def merge_two_df(df1: pd.DataFrame, df2: pd.DataFrame, on: list, exclude_cols: list) -> pd.DataFrame:
    # Combining df with df_kpmm_4
    df = pd.merge(
        df1,
        df2,
        on=on,
        how='left',
        suffixes=("", "_df2")
    )

    # drop only the df2 versions of excluded columns
    drop_cols = [f"{c}_df2" for c in exclude_cols if f"{c}_df2" in df.columns]
    df = df.drop(columns=drop_cols, errors="ignore")

    return df

In [30]:
def import_rasio() -> pd.DataFrame:
    """
    Import all Rasio data into one dataframe
    """

    exclude_cols = [
        'posisi',
        'company_name',
        'kbmi_type',
        'year',
        'quarter',
        'year_quarter',
        'company_date',
    ]
    
    # Path to this file's folder ("data")
    # base_path = Path(__file__).parent
    base_path = os.getcwd()
    # os.path.join(base_path, "FS from OJK", "Rasio", bank)

    # Build absolute paths to the Excel files
    file1 = os.path.join(base_path,  "summarized rasio - KBMI 1.xlsx")
    # Build absolute paths to the Excel files (KBMI 4)
    file4 = os.path.join(base_path,  "summarized rasio - KBMI 4.xlsx")
    file_aset_4 = os.path.join(base_path,  "summarized fitur aset - KBMI 4.xlsx")
    file_liabilitas_4 = os.path.join(base_path,  "summarized fitur liabilitas - KBMI 4.xlsx")
    file_kpmm_4 = os.path.join(base_path,  "summarized fitur kpmm - KBMI 4.xlsx")
    file_kualitas_4 = os.path.join(base_path,  "summarized fitur Kualitas Aset - KBMI 4.xlsx")
    file_laba_rugi_4 = os.path.join(base_path,  "summarized fitur Laba Rugi - KBMI 4.xlsx")
    file_lcr_nsfr_4 = os.path.join(base_path,  "summarized fitur lcr nsfr - KBMI 4.xlsx")

    # Build absolute paths to the Excel files (KBMI 2)
    file2 = os.path.join(base_path,  "summarized rasio - KBMI 2.xlsx")
    file_aset_2 = os.path.join(base_path,  "summarized fitur aset - KBMI 2.xlsx")
    file_liabilitas_2 = os.path.join(base_path,  "summarized fitur liabilitas - KBMI 2.xlsx")
    file_kpmm_2 = os.path.join(base_path,  "summarized fitur kpmm - KBMI 2.xlsx")
    file_kualitas_2 = os.path.join(base_path,  "summarized fitur Kualitas Aset - KBMI 2.xlsx")
    file_laba_rugi_2 = os.path.join(base_path,  "summarized fitur Laba Rugi - KBMI 2.xlsx")
    file_lcr_nsfr_2 = os.path.join(base_path,  "summarized fitur lcr nsfr - KBMI 2.xlsx")

    # Build absolute paths to the Excel files (KBMI 3)
    file3 = os.path.join(base_path,  "summarized rasio - KBMI 3.xlsx")
    file_aset_3 = os.path.join(base_path,  "summarized fitur aset - KBMI 3.xlsx")
    file_liabilitas_3 = os.path.join(base_path,  "summarized fitur liabilitas - KBMI 3.xlsx")
    file_kpmm_3 = os.path.join(base_path,  "summarized fitur kpmm - KBMI 3.xlsx")
    file_kualitas_3 = os.path.join(base_path,  "summarized fitur Kualitas Aset - KBMI 3.xlsx")
    file_laba_rugi_3 = os.path.join(base_path,  "summarized fitur Laba Rugi - KBMI 3.xlsx")
    file_lcr_nsfr_3 = os.path.join(base_path,  "summarized fitur lcr nsfr - KBMI 3.xlsx")

    # Read all data files
    df_kbmi_1 = pd.read_excel(file1)
    df_kbmi_1 = df_kbmi_1.drop(columns=["sort_key"], errors="ignore")

    df_kbmi_4 = pd.read_excel(file4)
    df_aset_4 = pd.read_excel(file_aset_4)
    df_liabilitas_4 = pd.read_excel(file_liabilitas_4)
    df_kpmm_4 = pd.read_excel(file_kpmm_4)
    df_kualitas_4 = pd.read_excel(file_kualitas_4)
    df_laba_rugi_4 = pd.read_excel(file_laba_rugi_4)
    df_lcr_nsfr_4 = pd.read_excel(file_lcr_nsfr_4)

    # Read KBMI 2 files
    df_kbmi_2 = pd.read_excel(file2)
    df_aset_2 = pd.read_excel(file_aset_2)
    df_liabilitas_2 = pd.read_excel(file_liabilitas_2)
    df_kpmm_2 = pd.read_excel(file_kpmm_2)
    df_kualitas_2 = pd.read_excel(file_kualitas_2)
    df_laba_rugi_2 = pd.read_excel(file_laba_rugi_2)
    # df_lcr_nsfr_2 = pd.read_excel(file_lcr_nsfr_2)

    # Read KBMI 3 files
    df_kbmi_3 = pd.read_excel(file3)
    df_aset_3 = pd.read_excel(file_aset_3)
    df_liabilitas_3 = pd.read_excel(file_liabilitas_3)
    df_kpmm_3 = pd.read_excel(file_kpmm_3)
    df_kualitas_3 = pd.read_excel(file_kualitas_3)
    df_laba_rugi_3 = pd.read_excel(file_laba_rugi_3)
    # df_lcr_nsfr_3 = pd.read_excel(file_lcr_nsfr_3)

    # Combining df rasio KBMI 1 and KBMI 4
    df = pd.concat([df_kbmi_1, df_kbmi_4], axis=0, join="outer", ignore_index=True)

    # Combining df with df_aset_4
    df = merge_two_df(df, df_aset_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_liabilitas_4
    df = merge_two_df(df, df_liabilitas_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_kpmm_4
    df = merge_two_df(df, df_kpmm_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_kualitas_4
    df = merge_two_df(df, df_kualitas_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_laba_rugi_4
    df = merge_two_df(df, df_laba_rugi_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_laba_rugi_4
    df = merge_two_df(df, df_lcr_nsfr_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining with KBMI 2 data
    df_all_2 = df_kbmi_2.copy()
    # Combining df with df_aset_2
    df_all_2 = merge_two_df(df_all_2, df_aset_2, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_liabilitas_2
    df_all_2 = merge_two_df(df_all_2, df_liabilitas_2, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_kpmm_2
    df_all_2 = merge_two_df(df_all_2, df_kpmm_2, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_kualitas_2
    df_all_2 = merge_two_df(df_all_2, df_kualitas_2, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_laba_rugi_2
    df_all_2 = merge_two_df(df_all_2, df_laba_rugi_2, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining with KBMI 3 data
    df_all_3 = df_kbmi_3.copy()
    # Combining df with df_aset_3
    df_all_3 = merge_two_df(df_all_3, df_aset_3, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_liabilitas_3
    df_all_3 = merge_two_df(df_all_3, df_liabilitas_3, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_kpmm_3
    df_all_3 = merge_two_df(df_all_3, df_kpmm_3, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_kualitas_3
    df_all_3 = merge_two_df(df_all_3, df_kualitas_3, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_laba_rugi_3
    df_all_3 = merge_two_df(df_all_3, df_laba_rugi_3, on=['posisi', 'company_name'], exclude_cols=exclude_cols)


    df_combined_kbmi_2_3_4 = pd.concat([df, df_all_2, df_all_3], axis=0, join="outer", ignore_index=True)

    return df_combined_kbmi_2_3_4

def import_fitur_rasio() -> list :
    fitur_rasio = [
        'aset_produktif_bermasalah_dan_aset_non_produktif_bermasalah_terhadap_total_aset_produktif_dan_aset_non_produktif',
        'cadangan_kerugian_penurunan_nilai_(ckpn)_aset_keuangan_terhadap_aset_produktif',
        'npl_gross',
        'npl_net',
        'return_on_asset',
        'return_on_equity',
        'net_interest_margin',
        'biaya_operasional_terhadap_pendapatan_operasional',
        'loan_to_deposit_ratio',
        'posisi_devisa_neto_(pdn)_secara_keseluruhan',

        # Fitur dari Aset
        'penempat_pada_bank_lain_per_total_aset',
        'tagihan_spot_derivatif_forward_per_total_aset',
        'surat_berharga_yang_dimiliki_per_total_aset',
        'reverse_repo_per_total_aset',
        'tagihan_akseptasi_per_total_aset',
        'kyd_dan_pembiayaan_syariah_per_total_aset',
        'ckpn_aset_keuangan_per_kyd_dan_pembiayaan_syariah',

        # Fitur dari Liabilitas
        'casa_ratio',
        'rim_ratio',

        # Fitur dari Modal
        'kpmm_per_car',
        'kpmm_cet1',
        'modal_terhadap_aset',
        'modal_terhadap_kredit_bersih',
        'other_comprehensive_income_to_equity',

        # Fitur dari Kualitas Aset
        'ckpn_per_kredit_restruk',
        'ckpn_stage_2_3_per_kredit_restruk',
        'kredit_bermasalah_dan_restruk_per_kredit_yang_diberikan',
        'kredit_restruk_per_modal_inti',
        'laba_per_kredit_bermasalah_non_restruk',
        'laba_per_kredit_restruk',
        'total_npl_dan_restruk_npl_per_kredit_yang_diberikan',

        # Fitur dari Laba Rugi
        # 'other_comprehensive_income',
        'kredit_restruk_per_pendapatan_bunga',

        # Fitur dari LCR dan NSFR
        'lcr',
        'nsfr',
    ]

    return(fitur_rasio)

def import_dictionary_rasio() -> dict :
    dict_rasio = {
        'aset_produktif_bermasalah_dan_aset_non_produktif_bermasalah_terhadap_total_aset_produktif_dan_aset_non_produktif': 'Aset Bermasalah per Total Aset',
        'cadangan_kerugian_penurunan_nilai_(ckpn)_aset_keuangan_terhadap_aset_produktif': 'CKPN per Aset Prod',
        'npl_gross': 'NPL Gross',
        'npl_net': 'NPL Net',
        'return_on_asset': 'ROA',
        'return_on_equity': 'ROE',
        'net_interest_margin': 'NIM',
        'biaya_operasional_terhadap_pendapatan_operasional': 'BOPO',
        'loan_to_deposit_ratio': 'LDR',
        'posisi_devisa_neto_(pdn)_secara_keseluruhan': 'PDN',

        # Fitur dari Aset
        'penempat_pada_bank_lain_per_total_aset' : 'Penempatan pada Bank Lain per Total Aset',
        'tagihan_spot_derivatif_forward_per_total_aset' : 'Tagihan Spot Derivatif Forward per Total Aset',
        'surat_berharga_yang_dimiliki_per_total_aset' : 'Surat Berharga yang Dimiliki per Total Aset',
        'reverse_repo_per_total_aset' : 'Reverse Repo per Total Aset',
        'tagihan_akseptasi_per_total_aset' : 'Tagihan Akseptasi per Total Aset',
        'kyd_dan_pembiayaan_syariah_per_total_aset' : 'KYD dan Pembiayaan Syariah per Total Aset',
        'ckpn_aset_keuangan_per_kyd_dan_pembiayaan_syariah' : 'CKPN Aset Keuangan per KYD dan Pembiayaan Syariah',

        # Fitur dari Liabilitas
        'casa_ratio' : 'CASA Ratio',
        'rim_ratio' : 'RIM Ratio',

        # Fitur dari Modal
        'kpmm_per_car' : 'KPMM per CAR',
        'kpmm_cet1' : 'KPMM CET-1',
        'modal_terhadap_aset' : 'Modal terhadap Aset',
        'modal_terhadap_kredit_bersih' : 'Modal terhadap Kredit Bersih',
        'other_comprehensive_income_to_equity' : 'Other Comprehensive Income',

        # Fitur dari Kualitas Aset
        'ckpn_per_kredit_restruk' : 'Total CKPN per Kredit Restruk',
        'ckpn_stage_2_3_per_kredit_restruk' : 'CKPN Stage 2 & 3 per Kredit Restruk',
        'kredit_bermasalah_dan_restruk_per_kredit_yang_diberikan' : 'Kredit yang Restruk + Kredit Bermasalah non Restruk per Kredit yang Diberikan',
        'kredit_restruk_per_modal_inti' : 'Kredit yang Restruk per Modal Inti',
        'laba_per_kredit_bermasalah_non_restruk' : 'Laba per Kredit Bermasalah non Restruk',
        'laba_per_kredit_restruk' : 'Laba per Kredit Restruk',
        'total_npl_dan_restruk_npl_per_kredit_yang_diberikan' : 'LAR Ratio',

        # Fitur dari Laba Rugi
        # 'other_comprehensive_income' : 'Other Comprehensive Income',
        'kredit_restruk_per_pendapatan_bunga' : 'Kredit Restruk per Pendapatan Bunga',

        # Fitur dari LCR dan NSFR
        'lcr' : 'LCR',
        'nsfr' : 'NSFR',
    }

    return(dict_rasio)

In [31]:
def import_fitur_rasio_kbmi_2() -> list :
    fitur_rasio = [
        'aset_produktif_bermasalah_dan_aset_non_produktif_bermasalah_terhadap_total_aset_produktif_dan_aset_non_produktif',
        'cadangan_kerugian_penurunan_nilai_(ckpn)_aset_keuangan_terhadap_aset_produktif',
        'npl_gross',
        'npl_net',
        'return_on_asset',
        'return_on_equity',
        'net_interest_margin',
        'biaya_operasional_terhadap_pendapatan_operasional',
        'loan_to_deposit_ratio',
        'posisi_devisa_neto_(pdn)_secara_keseluruhan',

        # Fitur dari Aset
        'penempat_pada_bank_lain_per_total_aset',
        'tagihan_spot_derivatif_forward_per_total_aset',
        'surat_berharga_yang_dimiliki_per_total_aset',
        'reverse_repo_per_total_aset',
        'tagihan_akseptasi_per_total_aset',
        'kyd_dan_pembiayaan_syariah_per_total_aset',
        'ckpn_aset_keuangan_per_kyd_dan_pembiayaan_syariah',

        # Fitur dari Liabilitas
        'casa_ratio',
        'rim_ratio',

        # Fitur dari Modal
        'kpmm_per_car',
        'kpmm_cet1',
        'modal_terhadap_aset',
        'modal_terhadap_kredit_bersih',
        'other_comprehensive_income_to_equity',

        # Fitur dari Kualitas Aset
        'ckpn_per_kredit_restruk',
        'ckpn_stage_2_3_per_kredit_restruk',
        'kredit_bermasalah_dan_restruk_per_kredit_yang_diberikan',
        'kredit_restruk_per_modal_inti',
        'laba_per_kredit_bermasalah_non_restruk',
        'laba_per_kredit_restruk',
        'total_npl_dan_restruk_npl_per_kredit_yang_diberikan',

        # Fitur dari Laba Rugi
        # 'other_comprehensive_income',
        'kredit_restruk_per_pendapatan_bunga',

        # Fitur dari LCR dan NSFR
        # 'lcr',
        # 'nsfr',
    ]

    return(fitur_rasio)

def import_dictionary_rasio_kbmi_2() -> dict :
    dict_rasio = {
        'aset_produktif_bermasalah_dan_aset_non_produktif_bermasalah_terhadap_total_aset_produktif_dan_aset_non_produktif': 'Aset Bermasalah per Total Aset',
        'cadangan_kerugian_penurunan_nilai_(ckpn)_aset_keuangan_terhadap_aset_produktif': 'CKPN per Aset Prod',
        'npl_gross': 'NPL Gross',
        'npl_net': 'NPL Net',
        'return_on_asset': 'ROA',
        'return_on_equity': 'ROE',
        'net_interest_margin': 'NIM',
        'biaya_operasional_terhadap_pendapatan_operasional': 'BOPO',
        'loan_to_deposit_ratio': 'LDR',
        'posisi_devisa_neto_(pdn)_secara_keseluruhan': 'PDN',

        # Fitur dari Aset
        'penempat_pada_bank_lain_per_total_aset' : 'Penempatan pada Bank Lain per Total Aset',
        'tagihan_spot_derivatif_forward_per_total_aset' : 'Tagihan Spot Derivatif Forward per Total Aset',
        'surat_berharga_yang_dimiliki_per_total_aset' : 'Surat Berharga yang Dimiliki per Total Aset',
        'reverse_repo_per_total_aset' : 'Reverse Repo per Total Aset',
        'tagihan_akseptasi_per_total_aset' : 'Tagihan Akseptasi per Total Aset',
        'kyd_dan_pembiayaan_syariah_per_total_aset' : 'KYD dan Pembiayaan Syariah per Total Aset',
        'ckpn_aset_keuangan_per_kyd_dan_pembiayaan_syariah' : 'CKPN Aset Keuangan per KYD dan Pembiayaan Syariah',

        # Fitur dari Liabilitas
        'casa_ratio' : 'CASA Ratio',
        'rim_ratio' : 'RIM Ratio',

        # Fitur dari Modal
        'kpmm_per_car' : 'KPMM per CAR',
        'kpmm_cet1' : 'KPMM CET-1',
        'modal_terhadap_aset' : 'Modal terhadap Aset',
        'modal_terhadap_kredit_bersih' : 'Modal terhadap Kredit Bersih',
        'other_comprehensive_income_to_equity' : 'Other Comprehensive Income',

        # Fitur dari Kualitas Aset
        'ckpn_per_kredit_restruk' : 'Total CKPN per Kredit Restruk',
        'ckpn_stage_2_3_per_kredit_restruk' : 'CKPN Stage 2 & 3 per Kredit Restruk',
        'kredit_bermasalah_dan_restruk_per_kredit_yang_diberikan' : 'Kredit yang Restruk + Kredit Bermasalah non Restruk per Kredit yang Diberikan',
        'kredit_restruk_per_modal_inti' : 'Kredit yang Restruk per Modal Inti',
        'laba_per_kredit_bermasalah_non_restruk' : 'Laba per Kredit Bermasalah non Restruk',
        'laba_per_kredit_restruk' : 'Laba per Kredit Restruk',
        'total_npl_dan_restruk_npl_per_kredit_yang_diberikan' : 'LAR Ratio',

        # Fitur dari Laba Rugi
        # 'other_comprehensive_income' : 'Other Comprehensive Income',
        'kredit_restruk_per_pendapatan_bunga' : 'Kredit Restruk per Pendapatan Bunga',

        # Fitur dari LCR dan NSFR
        # 'lcr' : 'LCR',
        # 'nsfr' : 'NSFR',
    }

    return(dict_rasio)

In [32]:
def import_fitur_rasio_kbmi_3() -> list :
    fitur_rasio = [
        'aset_produktif_bermasalah_dan_aset_non_produktif_bermasalah_terhadap_total_aset_produktif_dan_aset_non_produktif',
        'cadangan_kerugian_penurunan_nilai_(ckpn)_aset_keuangan_terhadap_aset_produktif',
        'npl_gross',
        'npl_net',
        'return_on_asset',
        'return_on_equity',
        'net_interest_margin',
        'biaya_operasional_terhadap_pendapatan_operasional',
        'loan_to_deposit_ratio',
        'posisi_devisa_neto_(pdn)_secara_keseluruhan',

        # Fitur dari Aset
        'penempat_pada_bank_lain_per_total_aset',
        'tagihan_spot_derivatif_forward_per_total_aset',
        'surat_berharga_yang_dimiliki_per_total_aset',
        'reverse_repo_per_total_aset',
        'tagihan_akseptasi_per_total_aset',
        'kyd_dan_pembiayaan_syariah_per_total_aset',
        'ckpn_aset_keuangan_per_kyd_dan_pembiayaan_syariah',

        # Fitur dari Liabilitas
        'casa_ratio',
        'rim_ratio',

        # Fitur dari Modal
        # 'kpmm_per_car',
        'kpmm_cet1',
        'modal_terhadap_aset',
        'modal_terhadap_kredit_bersih',
        'other_comprehensive_income_to_equity',

        # Fitur dari Kualitas Aset
        'ckpn_per_kredit_restruk',
        'ckpn_stage_2_3_per_kredit_restruk',
        'kredit_bermasalah_dan_restruk_per_kredit_yang_diberikan',
        'kredit_restruk_per_modal_inti',
        'laba_per_kredit_bermasalah_non_restruk',
        'laba_per_kredit_restruk',
        'total_npl_dan_restruk_npl_per_kredit_yang_diberikan',

        # Fitur dari Laba Rugi
        # 'other_comprehensive_income',
        'kredit_restruk_per_pendapatan_bunga',

        # Fitur dari LCR dan NSFR
        # 'lcr',
        # 'nsfr',
    ]

    return(fitur_rasio)

def import_dictionary_rasio_kbmi_3() -> dict :
    dict_rasio = {
        'aset_produktif_bermasalah_dan_aset_non_produktif_bermasalah_terhadap_total_aset_produktif_dan_aset_non_produktif': 'Aset Bermasalah per Total Aset',
        'cadangan_kerugian_penurunan_nilai_(ckpn)_aset_keuangan_terhadap_aset_produktif': 'CKPN per Aset Prod',
        'npl_gross': 'NPL Gross',
        'npl_net': 'NPL Net',
        'return_on_asset': 'ROA',
        'return_on_equity': 'ROE',
        'net_interest_margin': 'NIM',
        'biaya_operasional_terhadap_pendapatan_operasional': 'BOPO',
        'loan_to_deposit_ratio': 'LDR',
        'posisi_devisa_neto_(pdn)_secara_keseluruhan': 'PDN',

        # Fitur dari Aset
        'penempat_pada_bank_lain_per_total_aset' : 'Penempatan pada Bank Lain per Total Aset',
        'tagihan_spot_derivatif_forward_per_total_aset' : 'Tagihan Spot Derivatif Forward per Total Aset',
        'surat_berharga_yang_dimiliki_per_total_aset' : 'Surat Berharga yang Dimiliki per Total Aset',
        'reverse_repo_per_total_aset' : 'Reverse Repo per Total Aset',
        'tagihan_akseptasi_per_total_aset' : 'Tagihan Akseptasi per Total Aset',
        'kyd_dan_pembiayaan_syariah_per_total_aset' : 'KYD dan Pembiayaan Syariah per Total Aset',
        'ckpn_aset_keuangan_per_kyd_dan_pembiayaan_syariah' : 'CKPN Aset Keuangan per KYD dan Pembiayaan Syariah',

        # Fitur dari Liabilitas
        'casa_ratio' : 'CASA Ratio',
        'rim_ratio' : 'RIM Ratio',

        # Fitur dari Modal
        'kpmm_per_car' : 'KPMM per CAR',
        'kpmm_cet1' : 'KPMM CET-1',
        'modal_terhadap_aset' : 'Modal terhadap Aset',
        'modal_terhadap_kredit_bersih' : 'Modal terhadap Kredit Bersih',
        'other_comprehensive_income_to_equity' : 'Other Comprehensive Income',

        # Fitur dari Kualitas Aset
        'ckpn_per_kredit_restruk' : 'Total CKPN per Kredit Restruk',
        'ckpn_stage_2_3_per_kredit_restruk' : 'CKPN Stage 2 & 3 per Kredit Restruk',
        'kredit_bermasalah_dan_restruk_per_kredit_yang_diberikan' : 'Kredit yang Restruk + Kredit Bermasalah non Restruk per Kredit yang Diberikan',
        'kredit_restruk_per_modal_inti' : 'Kredit yang Restruk per Modal Inti',
        'laba_per_kredit_bermasalah_non_restruk' : 'Laba per Kredit Bermasalah non Restruk',
        'laba_per_kredit_restruk' : 'Laba per Kredit Restruk',
        'total_npl_dan_restruk_npl_per_kredit_yang_diberikan' : 'LAR Ratio',

        # Fitur dari Laba Rugi
        # 'other_comprehensive_income' : 'Other Comprehensive Income',
        'kredit_restruk_per_pendapatan_bunga' : 'Kredit Restruk per Pendapatan Bunga',

        # Fitur dari LCR dan NSFR
        # 'lcr' : 'LCR',
        # 'nsfr' : 'NSFR',
    }

    return(dict_rasio)

In [33]:
def import_numerik() -> pd.DataFrame:
    """
    Import all Rasio data into one dataframe
    """

    exclude_cols = [
        'posisi',
        'company_name',
        'kbmi_type',
        'year',
        'quarter',
        'year_quarter',
        'company_date',
    ]
    
    # Path to this file's folder ("data")
    # base_path = Path(__file__).parent
    base_path = os.getcwd()
    # os.path.join(base_path, "FS from OJK", "Rasio", bank)

    # Build absolute paths to the Excel files
    file4 = os.path.join(base_path, "summarized fitur Numeric - KBMI 4.xlsx")
    file2 = os.path.join(base_path, "summarized fitur Numeric - KBMI 2.xlsx")
    file3 = os.path.join(base_path, "summarized fitur Numeric - KBMI 3.xlsx")

    # Read all data files
    df_kbmi_4 = pd.read_excel(file4)
    df_kbmi_2 = pd.read_excel(file2)
    df_kbmi_3 = pd.read_excel(file3)

    # Combining df rasio KBMI 1 and KBMI 4
    df_combined_kbmi_2_3_4 = pd.concat([df_kbmi_4, df_kbmi_2, df_kbmi_3], axis=0, join="outer", ignore_index=True)

    # # Combining df with df_aset_4
    # df = merge_two_df(df, df_aset_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    return df_combined_kbmi_2_3_4

def import_fitur_numerik() -> list :
    fitur_numerik = [
        'total_ckpn_stage_2_dan_3',
        'total_npl_dan_restruk_npl',
    ]

    return(fitur_numerik)

def import_dictionary_numerik() -> dict :
    dict_numerik = {
        'total_ckpn_stage_2_dan_3': 'CKPN Stage 2 dan 3',
        'total_npl_dan_restruk_npl': 'Total NPL dan Restruk NPL',
    }

    return(dict_numerik)

## Main Code

In [34]:
exclude_cols = [
    'posisi',
    'company_name',
    'kbmi_type',
    'year',
    'quarter',
    'year_quarter',
    'company_date',
]

In [35]:
df_rasio = import_rasio()
fi_rasio = import_fitur_rasio()
column_rasio = exclude_cols + fi_rasio
dict_rasio = import_dictionary_rasio()

In [36]:
cleaned_rasio = df_rasio[column_rasio].rename(columns=dict_rasio)

In [37]:
cleaned_rasio

,posisi,company_name,kbmi_type,year,quarter,year_quarter,company_date,Aset Bermasalah per Total Aset,CKPN per Aset Prod,NPL Gross,...,Total CKPN per Kredit Restruk,CKPN Stage 2 & 3 per Kredit Restruk,Kredit yang Restruk + Kredit Bermasalah non Restruk per Kredit yang Diberikan,Kredit yang Restruk per Modal Inti,Laba per Kredit Bermasalah non Restruk,Laba per Kredit Restruk,LAR Ratio,Kredit Restruk per Pendapatan Bunga,LCR,NSFR
0,2022-03-31,BCA Digital,KBMI 1,2022,q1,2022_q1,BCA Digital_2022q1,0.0068,0.0018,0.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-06-30,BCA Digital,KBMI 1,2022,q2,2022_q2,BCA Digital_2022q2,0.0053,0.0040,0.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-09-30,BCA Digital,KBMI 1,2022,q3,2022_q3,BCA Digital_2022q3,0.0042,0.0027,0.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-12-31,BCA Digital,KBMI 1,2022,q4,2022_q4,BCA Digital_2022q4,0.0041,0.0056,0.0009,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-03-31,BCA Digital,KBMI 1,2023,q1,2023_q1,BCA Digital_2023q1,0.0044,0.0059,0.0027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,2024-12-31,"PT BANK PERMATA, Tbk",KBMI 3,2024,q4,2024_q4,"PT BANK PERMATA, Tbk_2024q4",0.0097,0.0483,0.0205,...,1.658931,0.934730,0.066314,0.180986,2.807275,0.490926,0.024532,0.422057,NaN,NaN
532,2024-12-31,"PT BANK SMBC INDONESIA, TBK (PT BANK BTPN, Tbk)",KBMI 3,2024,q4,2024_q4,"PT BANK SMBC INDONESIA, TBK (PT BANK BTPN, Tbk...",0.0060,0.0158,0.0138,...,0.583341,0.456507,0.042498,0.158428,2.163918,0.431269,0.013745,0.362134,NaN,NaN
533,2024-12-31,"PT BANK TABUNGAN NEGARA (PERSERO), Tbk",KBMI 3,2024,q4,2024_q4,"PT BANK TABUNGAN NEGARA (PERSERO), Tbk_2024q4",0.0262,0.0307,0.0316,...,0.236156,0.182441,0.188886,1.853998,0.749524,0.054369,0.036035,1.871833,NaN,NaN
534,2024-12-31,PT BANK UOB INDONESIA,KBMI 3,2024,q4,2024_q4,PT BANK UOB INDONESIA_2024q4,0.0070,0.0277,0.0205,...,0.753877,0.665900,0.062689,0.330454,0.403244,0.076833,0.020464,0.476016,NaN,NaN
535,2024-12-31,"PT PAN INDONESIA BANK, Tbk",KBMI 3,2024,q4,2024_q4,"PT PAN INDONESIA BANK, Tbk_2024q4",0.0250,0.0365,0.0292,...,0.432748,0.376494,0.139110,0.372256,2.005347,0.154387,0.029196,1.285043,NaN,NaN

In [38]:
df_numerik = import_numerik()
fi_numerik = import_fitur_numerik()
column_numerik = exclude_cols + fi_numerik
dict_numerik = import_dictionary_numerik()

In [39]:
cleaned_numerik = df_numerik[column_numerik].rename(columns=dict_numerik)

In [40]:
cleaned_numerik

,posisi,company_name,kbmi_type,year,quarter,year_quarter,company_date,CKPN Stage 2 dan 3,Total NPL dan Restruk NPL
0,2019-09-30,"PT BANK CENTRAL ASIA, Tbk",KBMI 4,2019,q3,2019_q3,"PT BANK CENTRAL ASIA, Tbk_2019q3",0,9246283
1,2019-09-30,PT BANK MANDIRI (PERSERO),KBMI 4,2019,q3,2019_q3,PT BANK MANDIRI (PERSERO)_2019q3,0,18974721
2,2019-09-30,"PT BANK NEGARA INDONESIA (PERSERO), Tbk",KBMI 4,2019,q3,2019_q3,"PT BANK NEGARA INDONESIA (PERSERO), Tbk_2019q3",0,9468447
3,2019-09-30,"PT BANK RAKYAT INDONESIA (PERSERO), Tbk",KBMI 4,2019,q3,2019_q3,"PT BANK RAKYAT INDONESIA (PERSERO), Tbk_2019q3",0,25183949
4,2019-12-31,"PT BANK CENTRAL ASIA, Tbk",KBMI 4,2019,q4,2019_q4,"PT BANK CENTRAL ASIA, Tbk_2019q4",0,7876926
...,...,...,...,...,...,...,...,...,...
483,2024-12-31,"PT BANK PERMATA, Tbk",KBMI 3,2024,q4,2024_q4,"PT BANK PERMATA, Tbk_2024q4",6790695,3157502
484,2024-12-31,"PT BANK SMBC INDONESIA, TBK (PT BANK BTPN, Tbk)",KBMI 3,2024,q4,2024_q4,"PT BANK SMBC INDONESIA, TBK (PT BANK BTPN, Tbk...",2360784,2005885
485,2024-12-31,"PT BANK TABUNGAN NEGARA (PERSERO), Tbk",KBMI 3,2024,q4,2024_q4,"PT BANK TABUNGAN NEGARA (PERSERO), Tbk_2024q4",10091390,11318003
486,2024-12-31,PT BANK UOB INDONESIA,KBMI 3,2024,q4,2024_q4,PT BANK UOB INDONESIA_2024q4,3520805,2054843
487,2024-12-31,"PT PAN INDONESIA BANK, Tbk",KBMI 3,2024,q4,2024_q4,"PT PAN INDONESIA BANK, Tbk_2024q4",6285622,3773709

In [41]:
cleaned_data = merge_two_df(cleaned_rasio, cleaned_numerik, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

In [42]:
# cleaned_data.to_excel("cleaned_all_data.xlsx", index=False)

# Code for Generating Pivot per Feature

## Import Library

In [43]:
import numpy as np
import pandas as pd
from typing import Tuple

## Additional Function

In [44]:
# ---------- Formatting functions ----------
def needs_percent_format(series: pd.Series) -> bool:
    """Heuristic: return True if values look like proportions (-1..1)"""
    if series.dropna().empty:
        return False
    smin = series.min()
    smax = series.max()
    return (smin >= -1.0 and smax <= 1.0)

def fmt_value(x, percent_mode: bool):
    if pd.isna(x):
        return ""
    try:
        if percent_mode:
            return f"{x:.2%}"
        # else numeric with thousands separators (or float 4 decimals)
        if float(x).is_integer():
            return f"{int(x):,}"
        return f"{x:,.4f}"
    except Exception:
        return str(x)

In [45]:
def generate_pivot_table_with_summaries(df_filtered: pd.DataFrame, column_to_check: str, percent_mode: bool=False) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Generate pivot table with column-wise and row-wise summaries
    """

    print(f"Generating pivot table for column: {column_to_check}")

    # Create column order (sorted by year ascending, quarter order Q1..Q4)
    quarter_order = ['q1', 'q2', 'q3', 'q4']
    
    # build a sorted list of (year, quarter) present
    unique_yq = df_filtered[['year', 'quarter']].drop_duplicates()
    unique_yq['q_order'] = unique_yq['quarter'].apply(lambda q: quarter_order.index(q) if q in quarter_order else 99)
    unique_yq = unique_yq.sort_values(['year', 'q_order'])
    col_tuples = [(int(r['year']), r['quarter']) for _, r in unique_yq.iterrows()]
    
    # pivot (agg mean in case of multiple rows per company-quarter)
    pivot = df_filtered.pivot_table(index='company_name',
                               columns=['year', 'quarter'],
                               values=column_to_check,
                               aggfunc='mean')
    
    # Reindex columns to ensure sorted order and present all col_tuples
    # Build MultiIndex in desired order
    ordered_cols = pd.MultiIndex.from_tuples(col_tuples, names=['year', 'quarter'])
    # Reindex to include missing columns as NaN if needed
    pivot = pivot.reindex(columns=ordered_cols, fill_value=np.nan)
    
    # ---------- Column-wise summary (bottom row) ----------
    col_stats = {}
    series_all = pivot  # DataFrame: rows companies, cols multiindex
    for col in pivot.columns:
        s = pivot[col].dropna()
        if s.empty:
            col_stats[col] = {k: np.nan for k in ["Min","P5","P15","Q1","Mean","Median","Q3","P85","P95","Max","Std"]}
            continue
        arr = s.values
        col_stats[col] = {
            "Min": np.nanmin(arr),
            "P5": np.nanpercentile(arr, 5),
            "P15": np.nanpercentile(arr, 15),
            "Q1": np.nanpercentile(arr, 25),
            "Mean": np.nanmean(arr),
            "Median": np.nanmedian(arr),
            "Q3": np.nanpercentile(arr, 75),
            "P85": np.nanpercentile(arr, 85),
            "P95": np.nanpercentile(arr, 95),
            "Max": np.nanmax(arr),
            "Std": np.nanstd(arr, ddof=0)
        }
    
    # Build bottom summary DataFrame with same MultiIndex columns
    bottom_df = pd.DataFrame({col: pd.Series(col_stats[col]) for col in pivot.columns})
    # bottom_df index = statistic keys; columns = MultiIndex
    # We'll transpose later for display if needed.
    
    # ---------- Row-wise summary (right side) ----------
    row_stats = []
    for idx, row in pivot.iterrows():
        vals = row.dropna().values
        if vals.size == 0:
            stats_row = {k: np.nan for k in ["Min","P5","P15","Q1","Mean","Median","Q3","P85","P95","Max","Std"]}
        else:
            stats_row = {
                "Min": np.nanmin(vals),
                "P5": np.nanpercentile(vals, 5),
                "P15": np.nanpercentile(vals, 15),
                "Q1": np.nanpercentile(vals, 25),
                "Mean": np.nanmean(vals),
                "Median": np.nanmedian(vals),
                "Q3": np.nanpercentile(vals, 75),
                "P85": np.nanpercentile(vals, 85),
                "P95": np.nanpercentile(vals, 95),
                "Max": np.nanmax(vals),
                "Std": np.nanstd(vals, ddof=0)
            }
        row_stats.append((idx, stats_row))
    
    row_stats_df = pd.DataFrame([s for _, s in row_stats], index=[r for r, _ in row_stats])
    # reorder columns
    row_stats_df = row_stats_df[["Min","P5","P15","Q1","Mean","Median","Q3","P85","P95","Max","Std"]]

    # ---------- Formatting decision ----------
    # percent_mode = needs_percent_format(pivot.stack(dropna=True) if not pivot.empty else pd.Series(dtype=float))

    # Format pivot for display: create display strings but keep numeric copies for downloads if desired
    # percent_mode = True  # force percent mode for this page
    display_pivot = pivot.copy().astype(float)
    display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))

    # Create bottom summary display (as a single-row DataFrame matching pivot columns)
    display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))

    # Create row summary display
    display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))

    return (display_pivot, display_bottom, display_row_stats)

In [46]:
def pivot_to_two_header_rows(pivot: pd.DataFrame):
    # pivot.columns is MultiIndex: (year, quarter)

    header_1 = [str(col[0]) for col in pivot.columns]   # year
    header_2 = [str(col[1]) for col in pivot.columns]   # quarter

    # Create a temporary DataFrame with 2 header rows + data
    df = pd.DataFrame([header_1, header_2] + pivot.reset_index().values.tolist())

    return df

def bottom_to_header_rows(bottom_df: pd.DataFrame):
    header_1 = [str(col[0]) for col in bottom_df.columns]
    header_2 = [str(col[1]) for col in bottom_df.columns]

    # Put statistic names as first column
    df = pd.DataFrame([ [""] + header_1,
                        ["Statistic"] + header_2 ])

    # Append the bottom summary values
    for stat_name, row in bottom_df.iterrows():
        df.loc[len(df)] = [stat_name] + row.tolist()

    return df

def row_summary_to_no_header(row_df: pd.DataFrame):
    # Row summary index = company_name
    # Columns = stats

    # Convert index to first column
    df = row_df.reset_index()

    # Create header row from column names
    header = df.columns.tolist()

    # Build dataframe: header + data rows
    final = pd.DataFrame([header] + df.values.tolist())

    return final

In [47]:
def concat_all_sections(pivot, bottom_df, row_summary):
    # Convert each to header-row format
    pivot_block = pivot_to_two_header_rows(pivot)
    bottom_block = bottom_to_header_rows(bottom_df)
    row_block = row_summary_to_no_header(row_summary)

    # Add a blank row between sections (optional)
    blank = pd.DataFrame([[""] * pivot_block.shape[1]])

    # Concatenate vertically
    combined = pd.concat(
        [pivot_block, blank,
         bottom_block, blank,
         row_block],
        ignore_index=True,
        sort=False
    )

    return combined

In [48]:
def _pivot_header_rows(pivot: pd.DataFrame) -> Tuple[list, list]:
    """
    Returns two lists: first_row (years), second_row (quarters) representing
    the MultiIndex columns of pivot.
    """
    # pivot.columns assumed MultiIndex (year, quarter)
    years = [str(c[0]) for c in pivot.columns]
    quarters = [str(c[1]) for c in pivot.columns]
    return years, quarters

def _row_summary_header_rows(row_stats_df: pd.DataFrame) -> Tuple[list, list]:
    """
    For the row-stats columns placed to the right, return header rows:
    - first row: blanks (same length as stats)
    - second row: the stat names (the column names of row_stats_df)
    """
    stats = list(row_stats_df.columns)
    first = [""] * len(stats)
    second = stats.copy()
    return first, second

In [49]:
def assemble_right_concat(pivot: pd.DataFrame,
                          bottom_df: pd.DataFrame,
                          row_stats_df: pd.DataFrame,
                          fill_na_for_bottom: object = "") -> pd.DataFrame:
    """
    Returns a single DataFrame ready to export, where:
    - pivot columns (MultiIndex) become the first two header rows
    - row_stats_df columns are appended to the right; their first header row is blank and second header row contains stat names
    - company rows contain pivot data + row stats
    - after company rows, a blank row is inserted, then bottom summary rows (statistics x pivot-columns).
      The appended row-summary columns will contain `fill_na_for_bottom` in those bottom rows (by default "")
    """
    # --- Validate shapes / indexes
    # Ensure pivot and bottom_df share the same MultiIndex columns
    if not isinstance(pivot.columns, pd.MultiIndex):
        raise ValueError("pivot.columns must be a MultiIndex (year, quarter).")

    # order pivot columns and bottom_df columns consistently
    pivot_cols = pivot.columns
    if not (isinstance(bottom_df.columns, pd.MultiIndex) and list(bottom_df.columns) == list(pivot_cols)):
        # try reindex bottom_df columns to pivot columns if possible
        try:
            bottom_df = bottom_df.reindex(columns=pivot_cols)
        except Exception:
            raise ValueError("bottom_df columns must match pivot MultiIndex columns (year, quarter).")

    # Reindex row_stats_df rows to pivot index order if necessary
    # Keep companies order as pivot.index
    row_stats_df_aligned = row_stats_df.reindex(index=pivot.index)

    # --- Header rows
    pivot_first_row, pivot_second_row = _pivot_header_rows(pivot)
    row_first_row, row_second_row = _row_summary_header_rows(row_stats_df_aligned)

    # Combine header rows: pivot headers + row-summary headers
    header_first = pivot_first_row + row_first_row
    header_second = pivot_second_row + row_second_row

    # --- Build data section (company rows)
    # pivot values (as a 2D array) and row stats values aligned by index
    pivot_values = pivot.reset_index(drop=False)  # keep company index in leftmost column if needed
    # We want combined table where index (company_name) is first column; but user requested "no column name" - we'll
    # put the company_name as first column in the data (not in header rows). To keep consistent with earlier style,
    # we'll include the company index as the very first column in the final DataFrame content, but header rows will not include its name.
    # Extract company names
    company_names = pivot_values[pivot.index.name if pivot.index.name else 'company_name'] if pivot.index.name in pivot_values.columns else pivot.index.values
    # Actually easier: keep pivot as values and prefix an index column manually:
    pivot_data_only = pivot.copy().reset_index()  # index becomes a column (company_name)
    # Now pivot_data_only.columns = ['company_name', (year,q), ...]
    # Extract pivot numeric columns (excluding the new company_name col)
    pivot_numeric_cols = pivot.columns

    # Compose combined data rows
    combined_rows = []
    # For each company in pivot.index order
    for company in pivot.index:
        # pivot row values (in pivot column order)
        pivot_row = list(pivot.loc[company, :].values)
        # row-stats values for this company (may contain NaN)
        if company in row_stats_df_aligned.index:
            row_stats_row = list(row_stats_df_aligned.loc[company].values)
        else:
            row_stats_row = [np.nan] * len(row_second_row)
        combined_rows.append([company] + pivot_row + row_stats_row)

    # Column labels for the combined DataFrame: create a flat list
    # We will produce a DataFrame where the *very first* column is "company" (no header rows for it)
    # The user asked "no column name, I want all those 3 dataframe use their column as first row", so we will
    # produce header rows that do NOT include a name for the company column.
    combined_col_labels = [""] + [f"{h1}||{h2}" for h1, h2 in zip(pivot_first_row, pivot_second_row)] + row_second_row

    # But we want to produce multi-row header representation, not actual MultiIndex. To export as requested:
    # Build a DataFrame where first two rows are header_first/header_second (prefixed by empty cell for the company column),
    # then the company rows, then a blank row, then bottom summary rows.
    # Build the top header block
    top_header_1 = [""] + pivot_first_row + row_first_row
    top_header_2 = [""] + pivot_second_row + row_second_row

    # Build company data rows as lists (company as first element)
    data_block = combined_rows  # each row: [company, pivot... , row_stats...]

    # Build bottom summary rows: bottom_df index are stats; we will produce one row per stat
    bottom_rows = []
    bottom_index_names = list(bottom_df.index)
    for stat_name in bottom_df.index:
        # values across pivot columns in pivot order
        vals = list(bottom_df.loc[stat_name, :].values)
        # for the right side (row-stats columns), we will fill with fill_na_for_bottom (or you can compute aggregates)
        right_fill = [fill_na_for_bottom] * len(row_second_row)
        bottom_rows.append([stat_name] + vals + right_fill)

    # Now assemble full list of rows as lists of strings/numbers:
    assembled = []
    assembled.append(top_header_1)
    assembled.append(top_header_2)
    # company rows
    for r in data_block:
        assembled.append(r)
    # blank separator row
    assembled.append([""] * (1 + len(pivot_first_row) + len(row_second_row)))
    # bottom rows (statistics)
    for r in bottom_rows:
        assembled.append(r)

    # Convert to DataFrame (no column names)
    combined_df = pd.DataFrame(assembled)

    # Optionally set dtypes for numeric columns: leave as-is (pandas will use object dtype because mixed)
    return combined_df

In [50]:
def add_custom_first_row(df: pd.DataFrame, text: str):
    # Create a new row with text in the first column, rest empty
    new_row = [text] + [""] * (df.shape[1] - 1)

    # Insert at the top
    df_with_header = pd.concat(
        [pd.DataFrame([new_row]), df],
        ignore_index=True
    )
    return df_with_header

In [51]:
def add_empty_rows_at_bottom(df: pd.DataFrame, n: int = 2):
    # Create n empty rows with same number of columns
    empty_rows = pd.DataFrame([[""] * df.shape[1] for _ in range(n)])
    return pd.concat([df, empty_rows], ignore_index=True)

## Main Code

### Code for Percentage Feature

In [52]:
# Placeholder for list of features that can be checked
list_columns_rasio = import_fitur_rasio()
list_columns_rasio_kbmi_2 = import_fitur_rasio_kbmi_2()
list_columns_rasio_kbmi_3 = import_fitur_rasio_kbmi_3()

# Placeholder for dictionary of features that can be checked
dict_rasio = import_dictionary_rasio()
dict_rasio_kbmi_2 = import_dictionary_rasio_kbmi_2()
dict_rasio_kbmi_3 = import_dictionary_rasio_kbmi_3()

In [53]:
df_filtered = cleaned_rasio.copy()
selected_kbmi = ["KBMI 3"]
selected_year = [2022, 2023, 2024]

mask_kbmi_type = df_filtered["kbmi_type"].isin(selected_kbmi) if selected_kbmi else True
mask_year = df_filtered["year"].isin(selected_year) if selected_year else True

# Filtered data based on company and date range
df_filtered = df_filtered[
    mask_kbmi_type & mask_year
]

In [54]:
df_filtered[['posisi', 'company_name', 'kbmi_type', 'year', 'quarter', 'KPMM per CAR']]

,posisi,company_name,kbmi_type,year,quarter,KPMM per CAR
416,2022-03-31,"PT BANK CIMB NIAGA, Tbk",KBMI 3,2022,q1,0.213065
417,2022-03-31,"PT BANK DANAMON INDONESIA, Tbk",KBMI 3,2022,q1,0.285385
418,2022-03-31,PT BANK HSBC INDONESIA,KBMI 3,2022,q1,0.294629
419,2022-03-31,"PT BANK MEGA, Tbk",KBMI 3,2022,q1,0.229278
420,2022-03-31,"PT BANK OCBC NISP, Tbk",KBMI 3,2022,q1,0.241026
...,...,...,...,...,...,...
531,2024-12-31,"PT BANK PERMATA, Tbk",KBMI 3,2024,q4,0.346469
532,2024-12-31,"PT BANK SMBC INDONESIA, TBK (PT BANK BTPN, Tbk)",KBMI 3,2024,q4,0.279868
533,2024-12-31,"PT BANK TABUNGAN NEGARA (PERSERO), Tbk",KBMI 3,2024,q4,0.185004
534,2024-12-31,PT BANK UOB INDONESIA,KBMI 3,2024,q4,0.165141
535,2024-12-31,"PT PAN INDONESIA BANK, Tbk",KBMI 3,2024,q4,0.351283

In [55]:
list_pivot_tables = []
list_bottom_summaries = []
list_row_summaries = []

# If its kbmi 2 or 3, use this dictionary and fitur list
if selected_kbmi == ["KBMI 2"] :
    list_columns_rasio = list_columns_rasio_kbmi_2
    dict_rasio = dict_rasio_kbmi_2

if selected_kbmi == ["KBMI 3"] :
    list_columns_rasio = list_columns_rasio_kbmi_3
    dict_rasio = dict_rasio_kbmi_3

for i in range (len(list_columns_rasio)):
    fitur_to_processed = dict_rasio.get(list_columns_rasio[i])
    list_pivot, list_bottom, list_row = generate_pivot_table_with_summaries(df_filtered, fitur_to_processed, percent_mode=True)
    list_pivot_tables.append(list_pivot)
    list_bottom_summaries.append(list_bottom)
    list_row_summaries.append(list_row)

Generating pivot table for column: Aset Bermasalah per Total Aset
Generating pivot table for column: CKPN per Aset Prod
Generating pivot table for column: NPL Gross
Generating pivot table for column: NPL Net
Generating pivot table for column: ROA
Generating pivot table for column: ROE

C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))

Generating pivot table for column: NIM
Generating pivot table for column: BOPO
Generating pivot table for column: LDR
Generating pivot table for column: PDN
Generating pivot table for column: Penempatan pada Bank Lain per Total Aset

C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))

Generating pivot table for column: Tagihan Spot Derivatif Forward per Total Aset
Generating pivot table for column: Surat Berharga yang Dimiliki per Total Aset
Generating pivot table for column: Reverse Repo per Total Aset
Generating pivot table for column: Tagihan Akseptasi per Total Aset
Generating pivot table for column: KYD dan Pembiayaan Syariah per Total Aset
Generating pivot table for column: CKPN Aset Keuangan per KYD dan Pembiayaan Syariah

C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))

Generating pivot table for column: CASA Ratio
Generating pivot table for column: RIM Ratio
Generating pivot table for column: KPMM CET-1
Generating pivot table for column: Modal terhadap Aset
Generating pivot table for column: Modal terhadap Kredit Bersih
Generating pivot table for column: Other Comprehensive Income

C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))

Generating pivot table for column: Total CKPN per Kredit Restruk
Generating pivot table for column: CKPN Stage 2 & 3 per Kredit Restruk
Generating pivot table for column: Kredit yang Restruk + Kredit Bermasalah non Restruk per Kredit yang Diberikan
Generating pivot table for column: Kredit yang Restruk per Modal Inti
Generating pivot table for column: Laba per Kredit Bermasalah non Restruk

C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))

Generating pivot table for column: Laba per Kredit Restruk
Generating pivot table for column: LAR Ratio
Generating pivot table for column: Kredit Restruk per Pendapatan Bunga

C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))

In [56]:
list_combined_tables = []
all_df_percentage = pd.DataFrame()

for i in range (len(list_columns_rasio)):
    combined = assemble_right_concat(list_pivot_tables[i], list_bottom_summaries[i], list_row_summaries[i])
    final_combined = add_custom_first_row(combined, dict_rasio.get(list_columns_rasio[i]))
    # Assuming final_df already includes your custom first row
    final_combined = add_empty_rows_at_bottom(final_combined, n=2)
    list_combined_tables.append(final_combined)
    all_df_percentage = pd.concat([all_df_percentage, final_combined], ignore_index=True)

In [ ]:
# all_df_percentage.to_excel("cleaned_pivot_all_data_percentage.xlsx", index=False, header=False)

### Code for Numeric Feature

In [57]:
# Placeholder for list of features that can be checked
list_columns_numerik = import_fitur_numerik()

# Placeholder for dictionary of features that can be checked
dict_numerik = import_dictionary_numerik()

In [58]:
df_filtered = cleaned_numerik.copy()
selected_kbmi = ["KBMI 3"]
selected_year = [2022, 2023, 2024]

mask_kbmi_type = df_filtered["kbmi_type"].isin(selected_kbmi) if selected_kbmi else True
mask_year = df_filtered["year"].isin(selected_year) if selected_year else True

# Filtered data based on company and date range
df_filtered = df_filtered[
    mask_kbmi_type & mask_year
]

In [59]:
list_pivot_tables = []
list_bottom_summaries = []
list_row_summaries = []

for i in range (len(list_columns_numerik)):
    fitur_to_processed = dict_numerik.get(list_columns_numerik[i])
    list_pivot, list_bottom, list_row = generate_pivot_table_with_summaries(df_filtered, fitur_to_processed, percent_mode=False)
    list_pivot_tables.append(list_pivot)
    list_bottom_summaries.append(list_bottom)
    list_row_summaries.append(list_row)

Generating pivot table for column: CKPN Stage 2 dan 3
Generating pivot table for column: Total NPL dan Restruk NPL

C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:89: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_pivot = display_pivot.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:92: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_bottom = bottom_df.applymap(lambda x: fmt_value(x, percent_mode))
C:\Users\Sharing Vision\AppData\Local\Temp\ipykernel_28536\3910324573.py:95: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  display_row_stats = row_stats_df.applymap(lambda x: fmt_value(x, percent_mode))

In [60]:
list_combined_tables = []
all_df_numerik = pd.DataFrame()

for i in range (len(list_columns_numerik)):
    combined = assemble_right_concat(list_pivot_tables[i], list_bottom_summaries[i], list_row_summaries[i])
    final_combined = add_custom_first_row(combined, dict_numerik.get(list_columns_numerik[i]))
    # Assuming final_df already includes your custom first row
    final_combined = add_empty_rows_at_bottom(final_combined, n=2)
    list_combined_tables.append(final_combined)
    all_df_numerik = pd.concat([all_df_numerik, final_combined], ignore_index=True)

In [ ]:
# all_df_numerik.to_excel("cleaned_pivot_all_data_numerik.xlsx", index=False, header=False)

### Combining Percentage and Numeric

In [61]:
all_df_percentage = add_empty_rows_at_bottom(all_df_percentage, n=2)
all_df = pd.concat([all_df_percentage, all_df_numerik], ignore_index=True)

In [62]:
all_df.to_excel("cleaned_pivot_all_data_kbmi_3.xlsx", index=False, header=False)